/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Cankıvanç
 */
public class SezarSifreleme extends javax.swing.JFrame {

    /**
     * Creates new form SezarSifreleme
     */
    public SezarSifreleme() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SifrelenmisMetin = new javax.swing.JTextField();
        SifrelenecekMetin = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        KaydirmaSayisi = new javax.swing.JTextField();
        Sifrele = new javax.swing.JButton();
        alfabe1 = new javax.swing.JLabel();
        alfabe2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(554, 355));
        setPreferredSize(new java.awt.Dimension(554, 355));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SifrelenmisMetin.setText("Sifrelenmis Metin");
        SifrelenmisMetin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SifrelenmisMetinActionPerformed(evt);
            }
        });
        getContentPane().add(SifrelenmisMetin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 450, -1));

        SifrelenecekMetin.setText("Sifrelenecek Metin");
        SifrelenecekMetin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SifrelenecekMetinMouseClicked(evt);
            }
        });
        SifrelenecekMetin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SifrelenecekMetinActionPerformed(evt);
            }
        });
        getContentPane().add(SifrelenecekMetin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 450, -1));

        jLabel1.setText("Kaydirma Sayisi :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 20));

        KaydirmaSayisi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        KaydirmaSayisi.setText("0");
        getContentPane().add(KaydirmaSayisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 40, -1));

        Sifrele.setText("Şifrele");
        Sifrele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SifreleActionPerformed(evt);
            }
        });
        getContentPane().add(Sifrele, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 100, -1));

        alfabe1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        alfabe1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        alfabe1.setText("abcçdefgğhıijklmnoöprsştuüvyz");
        getContentPane().add(alfabe1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 450, -1));

        alfabe2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        alfabe2.setForeground(new java.awt.Color(255, 0, 0));
        alfabe2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        alfabe2.setText("abcçdefgğhıijklmnoöprsştuüvyz");
        getContentPane().add(alfabe2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 450, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SifrelenmisMetinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SifrelenmisMetinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SifrelenmisMetinActionPerformed

    private void SifrelenecekMetinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SifrelenecekMetinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SifrelenecekMetinActionPerformed

    private void SifrelenecekMetinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SifrelenecekMetinMouseClicked
        // TODO add your handling code here:
        SifrelenecekMetin.setText("");
    }//GEN-LAST:event_SifrelenecekMetinMouseClicked

    private void SifreleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SifreleActionPerformed
        // TODO add your handling code here:
        int ks = Integer.parseInt(KaydirmaSayisi.getText());
        String alfabe = "abcçdefgğhıijklmnoöprsştuüvyz";
        String kAlfabe = "";
        String metin = SifrelenecekMetin.getText();
        String sifreliMetin = "";
        int uzunluk = metin.length();

        for (int i = ks; i < 29 + ks; i++) {
            kAlfabe += alfabe.charAt(i % 29);

        }

        for (int i = 0; i < uzunluk; i++) {
            for (int j = 0; j < 29; j++) {
                if (metin.charAt(i) == alfabe.charAt(j)) {
                    sifreliMetin += alfabe.charAt((j + ks) % 29);
                }
            }
        }

        alfabe2.setText(kAlfabe);
        SifrelenmisMetin.setText(sifreliMetin);


    }//GEN-LAST:event_SifreleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SezarSifreleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SezarSifreleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SezarSifreleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SezarSifreleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SezarSifreleme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField KaydirmaSayisi;
    private javax.swing.JButton Sifrele;
    private javax.swing.JTextField SifrelenecekMetin;
    private javax.swing.JTextField SifrelenmisMetin;
    private javax.swing.JLabel alfabe1;
    private javax.swing.JLabel alfabe2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
